import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Yuvraj Singh | Software Engineer",
  description: "Analytical Software Engineer and SIH 2025 Finalist with a strong foundation in Data Structures, Algorithms, and Object-Oriented Design. Experienced in building scalable distributed systems (Scrubbie) and AI-integrated platforms (Saaransh) using C++, Python, and Full-Stack technologies. Keenly interested in contributing to innovative research and organizational growth through technical excellence and a results-driven mindset.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
    "ai",
    "machine-learning",
    "python",
    "fastapi",
    "postgresql",
    "rgipt",
    "computer-science",
  ] as Array<string>,
  authors: {
    name: "Yuvraj Singh",
    url: "https://github.com/overlord00007",
  },
} as const;
